version: 2
jobs:
  build:
    docker:
      - image: library/debian:stretch
    steps:
      - run:
          name: install commands 
          command: bash .circleci/install_dependencies.sh
      - checkout
      - run:
          name: build 
          command: bash .circleci/build.sh
      - run:
          name: publish 
          command: bash .circleci/publish.sh
      - run:
          name: deploy
          command: bash .circleci/deploy-ssh.sh

workflows:
    version: 2
    build-n-deploy:
      jobs:
        - build:
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/