version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: install commands 
          command: echo $digital_ip && apt update && apt install expect openssh-client -y
      - run:
          name: deploy
          command: bash .circleci/deploy-ssh.sh