version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: install commands 
          command: bash .circleci/install_dependencies.sh
      - run:
          name: build 
          command: bash .circleci/build.sh
      - run:
          name: publish 
          command: bash .circleci/publish.sh
      - run:
          name: deploy
          command: bash .circleci/deploy-ssh.sh